package com.liferay.challenge.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the UsersCatastropheOrgs service. Represents a row in the &quot;Library_UsersCatastropheOrgs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.challenge.model.impl.UsersCatastropheOrgsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.challenge.model.impl.UsersCatastropheOrgsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UsersCatastropheOrgs
 * @see com.liferay.challenge.model.impl.UsersCatastropheOrgsImpl
 * @see com.liferay.challenge.model.impl.UsersCatastropheOrgsModelImpl
 * @generated
 */
public interface UsersCatastropheOrgsModel extends BaseModel<UsersCatastropheOrgs> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a users catastrophe orgs model instance should use the {@link UsersCatastropheOrgs} interface instead.
     */

    /**
     * Returns the primary key of this users catastrophe orgs.
     *
     * @return the primary key of this users catastrophe orgs
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this users catastrophe orgs.
     *
     * @param primaryKey the primary key of this users catastrophe orgs
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the user ID of this users catastrophe orgs.
     *
     * @return the user ID of this users catastrophe orgs
     */
    public long getUserId();

    /**
     * Sets the user ID of this users catastrophe orgs.
     *
     * @param userId the user ID of this users catastrophe orgs
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this users catastrophe orgs.
     *
     * @return the user uuid of this users catastrophe orgs
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this users catastrophe orgs.
     *
     * @param userUuid the user uuid of this users catastrophe orgs
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the organization ID of this users catastrophe orgs.
     *
     * @return the organization ID of this users catastrophe orgs
     */
    public long getOrganizationId();

    /**
     * Sets the organization ID of this users catastrophe orgs.
     *
     * @param organizationId the organization ID of this users catastrophe orgs
     */
    public void setOrganizationId(long organizationId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.liferay.challenge.model.UsersCatastropheOrgs usersCatastropheOrgs);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.liferay.challenge.model.UsersCatastropheOrgs> toCacheModel();

    @Override
    public com.liferay.challenge.model.UsersCatastropheOrgs toEscapedModel();

    @Override
    public com.liferay.challenge.model.UsersCatastropheOrgs toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
