package com.liferay.challenge.service.base;

import com.liferay.challenge.model.UsersCatastropheOrgs;
import com.liferay.challenge.service.UsersCatastropheOrgsService;
import com.liferay.challenge.service.persistence.UsersCatastropheOrgsPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the users catastrophe orgs remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.challenge.service.impl.UsersCatastropheOrgsServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.challenge.service.impl.UsersCatastropheOrgsServiceImpl
 * @see com.liferay.challenge.service.UsersCatastropheOrgsServiceUtil
 * @generated
 */
public abstract class UsersCatastropheOrgsServiceBaseImpl
    extends BaseServiceImpl implements UsersCatastropheOrgsService,
        IdentifiableBean {
    @BeanReference(type = com.liferay.challenge.service.UsersCatastropheOrgsLocalService.class)
    protected com.liferay.challenge.service.UsersCatastropheOrgsLocalService usersCatastropheOrgsLocalService;
    @BeanReference(type = com.liferay.challenge.service.UsersCatastropheOrgsService.class)
    protected com.liferay.challenge.service.UsersCatastropheOrgsService usersCatastropheOrgsService;
    @BeanReference(type = UsersCatastropheOrgsPersistence.class)
    protected UsersCatastropheOrgsPersistence usersCatastropheOrgsPersistence;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private UsersCatastropheOrgsServiceClpInvoker _clpInvoker = new UsersCatastropheOrgsServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.liferay.challenge.service.UsersCatastropheOrgsServiceUtil} to access the users catastrophe orgs remote service.
     */

    /**
     * Returns the users catastrophe orgs local service.
     *
     * @return the users catastrophe orgs local service
     */
    public com.liferay.challenge.service.UsersCatastropheOrgsLocalService getUsersCatastropheOrgsLocalService() {
        return usersCatastropheOrgsLocalService;
    }

    /**
     * Sets the users catastrophe orgs local service.
     *
     * @param usersCatastropheOrgsLocalService the users catastrophe orgs local service
     */
    public void setUsersCatastropheOrgsLocalService(
        com.liferay.challenge.service.UsersCatastropheOrgsLocalService usersCatastropheOrgsLocalService) {
        this.usersCatastropheOrgsLocalService = usersCatastropheOrgsLocalService;
    }

    /**
     * Returns the users catastrophe orgs remote service.
     *
     * @return the users catastrophe orgs remote service
     */
    public com.liferay.challenge.service.UsersCatastropheOrgsService getUsersCatastropheOrgsService() {
        return usersCatastropheOrgsService;
    }

    /**
     * Sets the users catastrophe orgs remote service.
     *
     * @param usersCatastropheOrgsService the users catastrophe orgs remote service
     */
    public void setUsersCatastropheOrgsService(
        com.liferay.challenge.service.UsersCatastropheOrgsService usersCatastropheOrgsService) {
        this.usersCatastropheOrgsService = usersCatastropheOrgsService;
    }

    /**
     * Returns the users catastrophe orgs persistence.
     *
     * @return the users catastrophe orgs persistence
     */
    public UsersCatastropheOrgsPersistence getUsersCatastropheOrgsPersistence() {
        return usersCatastropheOrgsPersistence;
    }

    /**
     * Sets the users catastrophe orgs persistence.
     *
     * @param usersCatastropheOrgsPersistence the users catastrophe orgs persistence
     */
    public void setUsersCatastropheOrgsPersistence(
        UsersCatastropheOrgsPersistence usersCatastropheOrgsPersistence) {
        this.usersCatastropheOrgsPersistence = usersCatastropheOrgsPersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();
    }

    public void destroy() {
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return UsersCatastropheOrgs.class;
    }

    protected String getModelClassName() {
        return UsersCatastropheOrgs.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = usersCatastropheOrgsPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
