package com.liferay.challenge.model.impl;

import com.liferay.challenge.model.UsersCatastropheOrgs;
import com.liferay.challenge.model.UsersCatastropheOrgsModel;
import com.liferay.challenge.model.UsersCatastropheOrgsSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the UsersCatastropheOrgs service. Represents a row in the &quot;Library_UsersCatastropheOrgs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.challenge.model.UsersCatastropheOrgsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UsersCatastropheOrgsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UsersCatastropheOrgsImpl
 * @see com.liferay.challenge.model.UsersCatastropheOrgs
 * @see com.liferay.challenge.model.UsersCatastropheOrgsModel
 * @generated
 */
@JSON(strict = true)
public class UsersCatastropheOrgsModelImpl extends BaseModelImpl<UsersCatastropheOrgs>
    implements UsersCatastropheOrgsModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a users catastrophe orgs model instance should use the {@link com.liferay.challenge.model.UsersCatastropheOrgs} interface instead.
     */
    public static final String TABLE_NAME = "Library_UsersCatastropheOrgs";
    public static final Object[][] TABLE_COLUMNS = {
            { "userId", Types.BIGINT },
            { "organizationId", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table Library_UsersCatastropheOrgs (userId LONG not null primary key,organizationId LONG)";
    public static final String TABLE_SQL_DROP = "drop table Library_UsersCatastropheOrgs";
    public static final String ORDER_BY_JPQL = " ORDER BY usersCatastropheOrgs.userId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY Library_UsersCatastropheOrgs.userId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.liferay.challenge.model.UsersCatastropheOrgs"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.liferay.challenge.model.UsersCatastropheOrgs"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.liferay.challenge.model.UsersCatastropheOrgs"));
    private static ClassLoader _classLoader = UsersCatastropheOrgs.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            UsersCatastropheOrgs.class
        };
    private long _userId;
    private String _userUuid;
    private long _organizationId;
    private UsersCatastropheOrgs _escapedModel;

    public UsersCatastropheOrgsModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static UsersCatastropheOrgs toModel(
        UsersCatastropheOrgsSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        UsersCatastropheOrgs model = new UsersCatastropheOrgsImpl();

        model.setUserId(soapModel.getUserId());
        model.setOrganizationId(soapModel.getOrganizationId());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<UsersCatastropheOrgs> toModels(
        UsersCatastropheOrgsSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<UsersCatastropheOrgs> models = new ArrayList<UsersCatastropheOrgs>(soapModels.length);

        for (UsersCatastropheOrgsSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _userId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setUserId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _userId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return UsersCatastropheOrgs.class;
    }

    @Override
    public String getModelClassName() {
        return UsersCatastropheOrgs.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("userId", getUserId());
        attributes.put("organizationId", getOrganizationId());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        Long organizationId = (Long) attributes.get("organizationId");

        if (organizationId != null) {
            setOrganizationId(organizationId);
        }
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public long getOrganizationId() {
        return _organizationId;
    }

    @Override
    public void setOrganizationId(long organizationId) {
        _organizationId = organizationId;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            UsersCatastropheOrgs.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public UsersCatastropheOrgs toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (UsersCatastropheOrgs) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        UsersCatastropheOrgsImpl usersCatastropheOrgsImpl = new UsersCatastropheOrgsImpl();

        usersCatastropheOrgsImpl.setUserId(getUserId());
        usersCatastropheOrgsImpl.setOrganizationId(getOrganizationId());

        usersCatastropheOrgsImpl.resetOriginalValues();

        return usersCatastropheOrgsImpl;
    }

    @Override
    public int compareTo(UsersCatastropheOrgs usersCatastropheOrgs) {
        long primaryKey = usersCatastropheOrgs.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof UsersCatastropheOrgs)) {
            return false;
        }

        UsersCatastropheOrgs usersCatastropheOrgs = (UsersCatastropheOrgs) obj;

        long primaryKey = usersCatastropheOrgs.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<UsersCatastropheOrgs> toCacheModel() {
        UsersCatastropheOrgsCacheModel usersCatastropheOrgsCacheModel = new UsersCatastropheOrgsCacheModel();

        usersCatastropheOrgsCacheModel.userId = getUserId();

        usersCatastropheOrgsCacheModel.organizationId = getOrganizationId();

        return usersCatastropheOrgsCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(5);

        sb.append("{userId=");
        sb.append(getUserId());
        sb.append(", organizationId=");
        sb.append(getOrganizationId());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(10);

        sb.append("<model><model-name>");
        sb.append("com.liferay.challenge.model.UsersCatastropheOrgs");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>organizationId</column-name><column-value><![CDATA[");
        sb.append(getOrganizationId());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
